platform :ios, '8.0'

target 'ZombieCafe' do
    pod 'Mixpanel', '~> 3.0.0'
    pod 'FyberSDK', '~> 8.5.0'
    pod 'Adjust', '~> 4.10.0'
    pod 'SwrveSDK', '~> 4.6.0.0'
    pod 'Firebase/Core'
    pod 'Firebase/Analytics'
    pod 'jsoncpp', '~> 1.6.5'
end

workspace 'ZombieCafe'

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['SDKROOT'] = 'iphoneos'
        end
    end
    
    installer_representation.pods_project.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['SDKROOT'] = 'iphoneos'
    end
end
